# Permalinks
permalink:        pretty

# Setup
title:            Sun
tagline:          A language for rapid prototyping and learning new concepts
description:      A language for rapid prototyping and learning new concepts. Made by @mavenave
url:              http://mavenave.me
baseurl:          '/sun'

author:
  name:           Chan Guan Hao
  url:            http://mavenave.me/sun

github:
  repo:           https://github.com/mavenave/sun

kramdown:
  input:          GFM
